
services:
  web:
    build: "./fit-assistant"
    # env_file: "./fit-assistant/.env"
    container_name: web
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=postgresql://${PG_USER-fitness}:${PG_DATABASE:-fitness}@db:$PG_PORT/${PG_DATABASE:-fitness_db}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=${PG_DATABASE:-pokemon}
      - POSTGRES_USER=${PG_USER:-pokemon}
      - POSTGRES_PASSWORD=${PG_DATABASE:-pokemon}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${PG_PORT:-5432}", "-U", "${PG_USER}"]
      interval: 60s
      timeout: 20s
      retries: 3

volumes:
  postgres-data:
