import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {
  Box,
  Container,
  CssBaseline,
  ThemeProvider
} from '@mui/material'
import Header from '@/components/Header/Header'
import { Suspense } from 'react'
import Loader from '@/components/Loader/Loader'
import theme from '@/theme/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Header />
          <Box className="flex flex-1 h-screen">
            <Container>
              <Suspense fallback={<Loader />}>{children}</Suspense>
            </Container>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  )
}
